# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone

try:
    own_cart_model = settings.CART_MODEL
except AttributeError:
    own_cart_model = None


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='unit price')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('cart',),
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]

    if not own_cart_model:

        operations.append(
            migrations.CreateModel(
                name='Cart',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                    ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
                ],
                options={
                    'ordering': ('-creation_date',),
                    'abstract': False,
                    'verbose_name': 'cart',
                    'verbose_name_plural': 'carts',
                },
            )
        )
        operations.append(
            migrations.AddField(
                model_name='cart',
                name='items',
                field=models.ManyToManyField(related_name='cart', to='changuito.Item', verbose_name='items'),
            )
        )
        operations.append(
            migrations.AddField(
                model_name='cart',
                name='user',
                field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                        to=settings.AUTH_USER_MODEL),
            )
        )
